=== logicahealth/InfoButtons/oib-request/oib-profile-schema/src/main/resources/TerminologyInference.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com) by 
	Guilherme Del Fiol (Duke University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:altova="http://www.altova.com/xml-schema-extensions"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="terminologyInference">
		<xs:annotation>
			<xs:documentation>Comment describing your root element
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" />
				<xs:element name="targetCodeSystem" type="Id" />
				<xs:element name="codeInference" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sourceCodeSystem" type="Id">
								<xs:annotation>
									<xs:documentation>Defines the source code system for which a
										particular codeInference applies.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="inferenceDefinition">
								<xs:annotation>
									<xs:documentation>Defiens the inference for a particular code
										system
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:choice>
										<xs:element name="localMappings">
											<xs:annotation>
												<xs:documentation>Simple one-to-one code translations
													defined locally within the resource profile instance. Used
													for code translations that refer to a small set of codes
													(e.g., gender, age group).
												</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="mapping" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="sourceValue" type="xs:string"
																use="required" />
															<xs:attribute name="targetValue" type="xs:string"
																use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="externalDefinition">
											<xs:annotation>
												<xs:documentation>Code transofrmation defined as a reference
													to an external terminology inference definition. Used for
													more complex transformations that involve one or more
													semantic navigation steps.
												</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="traverseAssociation"
														minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:complexContent>
																<xs:extension base="CD">
																	<xs:attribute name="sequence" use="required" />
																	<xs:attribute name="direction" use="required">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="DIRECT" />
																				<xs:enumeration value="INVERSE" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																	<xs:attribute name="maxConcepts" type="xs:int" />
																</xs:extension>
															</xs:complexContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="codeProperty" type="Id" />
													<xs:element name="displayNameProperty" type="Id" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="keywordInference" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="searchCodeSystem" type="Id" />
							<xs:element name="codeProperty" type="Id" />
							<xs:element name="displayNameProperty" type="Id" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="callInferenceByName" type="ST"
					minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Id">
		<xs:attribute name="id" use="required" />
		<xs:attribute name="name" use="required" />
	</xs:complexType>
	<xs:complexType name="CD">
		<xs:sequence>
			<xs:element name="code">
				<xs:complexType>
					<xs:attribute name="code" use="required" />
					<xs:attribute name="codeSystem" use="required" />
					<xs:attribute name="codeSystemName" />
					<xs:attribute name="displayName" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ST">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="description" type="ST" />
</xs:schema>

=== logicahealth/InfoButtons/infobutton-kbschema/src/main/resources/ResourceProfiles/MeSH_Age_To_MDConsult.xml
<?xml version="1.0" encoding="UTF-8"?>
<terminologyInference xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TerminologyInference.xsd">
	<description>Translates MeSH Age groups into ClinicalTrials.gov proprietary age group keywords</description>
	<targetCodeSystem name="Clinical trials.gov age groups" id="ClinicalTrials.gov"/>
	<codeInference>
		<sourceCodeSystem id="2.16.840.1.113883.6.177" name="MeSH"/>
		<inferenceDefinition>
			<localMappings>
				<mapping targetValue="infant, newborn" sourceValue="D007231"/>
				<mapping targetValue="infant" sourceValue="D007223"/>
				<mapping targetValue="child, preschool" sourceValue="D002675"/>
				<mapping targetValue="child" sourceValue="D002648"/>
				<mapping targetValue="adolescence" sourceValue="D000293"/>
				<mapping targetValue="adult" sourceValue="D055815"/>
				<mapping targetValue="adult" sourceValue="D000328"/>
				<mapping targetValue="middle age" sourceValue="D008875"/>
				<mapping targetValue="aged" sourceValue="D000368"/>
				<mapping targetValue="aged" sourceValue="D000369"/>
			</localMappings>
		</inferenceDefinition>
	</codeInference>
</terminologyInference>

=== logicahealth/InfoButtons/infobutton-kbschema/src/main/resources/ResourceProfiles/TerminologyInference_to_ICD9CM.xml
<?xml version="1.0" encoding="UTF-8"?>
<terminologyInference xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TerminologyInference.xsd">
	<description>Defines mappings from multiple source systems to ICD9-CM</description>
	<targetCodeSystem name="ICD9-CM" id="2.16.840.1.113883.6.2"/>
	<codeInference>
		<sourceCodeSystem name="SNOMED CT" id="SNOMED CT"/>
		<inferenceDefinition>
			<externalDefinition>
				<codeProperty name="Mapping from SNOMED-CT to ICD9-CM" id="SNOMED_ICD_9_MAP"/>
				<displayNameProperty name="Preferred Synonym" id="Synonym"/>
			</externalDefinition>
		</inferenceDefinition>
	</codeInference>
	<keywordInference>
		<searchCodeSystem id="ICD-9-CM" name="International Classification of Diseases 9 - Clinical Modification"/>
		<codeProperty name="Mapping from SNOMED-CT to ICD9-CM" id="SNOMED_ICD_9_MAP"/>
		<displayNameProperty name="Preferred Synonym" id="Synonym"/>
	</keywordInference>
</terminologyInference>

=== logicahealth/InfoButtons/infobutton-kbschema/src/main/resources/ResourceProfiles/MeSH_To_ClinicalTrials.xml
<?xml version="1.0" encoding="UTF-8"?>
<terminologyInference xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TerminologyInference.xsd">
	<description>Translates MeSH Age groups into ClinicalTrials.gov proprietary age group keywords</description>
	<targetCodeSystem name="Clinical trials.gov age groups" id="ClinicalTrials.gov"/>
	<codeInference>
		<sourceCodeSystem id="2.16.840.1.113883.6.177" name="MeSH"/>
		<inferenceDefinition>
			<localMappings>
				<mapping targetValue="0" sourceValue="D007231"/>
				<mapping targetValue="0" sourceValue="D007223"/>
				<mapping targetValue="0" sourceValue="D002675"/>
				<mapping targetValue="0" sourceValue="D002648"/>
				<mapping targetValue="0" sourceValue="D000293"/>
				<mapping targetValue="1" sourceValue="D055815"/>
				<mapping targetValue="1" sourceValue="D000328"/>
				<mapping targetValue="1" sourceValue="D008875"/>
				<mapping targetValue="2" sourceValue="D000368"/>
				<mapping targetValue="2" sourceValue="D000369"/>
			</localMappings>
		</inferenceDefinition>
	</codeInference>
</terminologyInference>
